export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const REGISTER_ADDRESS = 'REGISTER_ADDRESS';
export const ADD_USER_PET = 'ADD_USER_PET';
export const CHECK_USER_STATUS = 'CHECK_USER_STATUS';
export const ADD_USER_MATCH = 'ADD_USER_MATCH';
